# Generated by Django 6.0.6 on 2026-06-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveGap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(default='radar', max_length=20)),
                ('gap_start', models.DateTimeField()),
                ('gap_end', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('detail', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'archive_gap',
                'indexes': [models.Index(fields=['service', 'gap_start'], name='archive_gap_service_24e3fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='RadarFrame',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('tile_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(max_length=10)),
                ('missing', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'radar_frame',
                'indexes': [models.Index(fields=['timestamp'], name='radar_frame_timesta_48c392_idx')],
            },
        ),
    ]
