"""Create the monthly-partitioned ``lightning_strike`` table.

Django does not emit ``PARTITION BY``, so the table is built with **raw SQL**
inside a :class:`~django.db.migrations.SeparateDatabaseAndState`: the database
gets a RANGE-partitioned table (+ a ``DEFAULT`` safety-net partition + the
current and next two month partitions, computed in UTC — not hardcoded), while
Django's migration *state* gets a normal (``managed=False``) model for ORM use.

On non-PostgreSQL backends (the sqlite host fallback — the suite itself runs
dockerized against Postgres) a plain, non-partitioned table is created so
the schema still loads; the partition-specific tests skip on non-Postgres.
"""

from __future__ import annotations

from django.db import migrations
from django.db import models

# PostgreSQL: declarative monthly RANGE partitioning by struck_at. The PK must
# include the partition key; the explicit index propagates to every partition.
_CREATE_PG = """
CREATE TABLE lightning_strike (
    id        bigint GENERATED BY DEFAULT AS IDENTITY,
    struck_at timestamptz NOT NULL,
    lat       real,
    lon       real,
    intensity smallint,
    PRIMARY KEY (id, struck_at)
) PARTITION BY RANGE (struck_at);

CREATE INDEX lightning_strike_struck_at_idx ON lightning_strike (struck_at);

CREATE TABLE lightning_strike_default PARTITION OF lightning_strike DEFAULT;
"""

# Non-Postgres fallback (sqlite): a plain table, no partitioning.
_CREATE_GENERIC = """
CREATE TABLE lightning_strike (
    id        integer PRIMARY KEY AUTOINCREMENT,
    struck_at timestamp NOT NULL,
    lat       real,
    lon       real,
    intensity smallint
);
CREATE INDEX lightning_strike_struck_at_idx ON lightning_strike (struck_at);
"""


def create_table(_apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "postgresql":
        with conn.cursor() as cursor:
            cursor.execute(_CREATE_PG)
        # Pre-create current + next two months so inserts never hit DEFAULT on
        # the 1st. Reuses the partition helper's single DDL path.
        from radar.lightning import partitions  # noqa: PLC0415

        with conn.cursor() as cursor:
            partitions.create_month_partitions(
                cursor,
                partitions.months_from(partitions.current_month_utc(), 2),
            )
    else:
        with conn.cursor() as cursor:
            cursor.executescript(_CREATE_GENERIC)


def drop_table(_apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS lightning_strike CASCADE")


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="LightningStrike",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("struck_at", models.DateTimeField()),
                        ("lat", models.FloatField(null=True)),
                        ("lon", models.FloatField(null=True)),
                        ("intensity", models.SmallIntegerField(null=True)),
                    ],
                    options={
                        "db_table": "lightning_strike",
                        "managed": False,
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(create_table, drop_table),
            ],
        ),
    ]
