"""Provider-scope the radar archive.

Both providers emit epoch timestamps that can collide on shared 600 s boundaries,
so ``timestamp`` alone can no longer be the ``radar_frame`` primary key. This
migration swaps in a surrogate ``BigAutoField id`` PK, keeps ``timestamp`` as a
plain ``BIGINT``, and makes ``(provider, timestamp)`` the identity (unique
constraint + composite index). ``archive_gap`` gains a ``provider`` column
(default ``rainviewer`` for rows written before provider scoping).

Expand-only in effect: the PK swap rewrites a ~13 k-row table (instant); during a
deploy overlap old code still works because — with only rainviewer rows present —
``(provider, timestamp)`` is effectively unique on ``timestamp``, and its inserts
omit ``id`` (the DB IDENTITY fills it server-side).

Django's autogenerated version adds the new PK *before* dropping the old one,
which Postgres rejects on a populated table ("multiple primary keys ... not
allowed"). So the database step is explicit and correctly ordered, wrapped in a
:class:`SeparateDatabaseAndState` whose state half matches the ORM model (keeping
``makemigrations --check`` green). A non-PostgreSQL host fallback (sqlite) rebuilds
the table via the schema editor, exactly like migration 0002's dual path.
"""

from __future__ import annotations

from django.db import migrations
from django.db import models

_FORWARD_PG = """
ALTER TABLE archive_gap ADD COLUMN provider varchar(20) NOT NULL DEFAULT 'rainviewer';
ALTER TABLE radar_frame DROP CONSTRAINT radar_frame_pkey;
ALTER TABLE radar_frame ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE radar_frame ADD PRIMARY KEY (id);
CREATE INDEX radar_frame_provider_ts_idx ON radar_frame (provider, timestamp);
ALTER TABLE radar_frame ADD CONSTRAINT radar_frame_provider_ts_uniq UNIQUE (provider, timestamp);
"""

_REVERSE_PG = """
ALTER TABLE radar_frame DROP CONSTRAINT radar_frame_provider_ts_uniq;
DROP INDEX radar_frame_provider_ts_idx;
ALTER TABLE radar_frame DROP CONSTRAINT radar_frame_pkey;
ALTER TABLE radar_frame DROP COLUMN id;
ALTER TABLE radar_frame ADD PRIMARY KEY (timestamp);
ALTER TABLE archive_gap DROP COLUMN provider;
"""

# The state half — what Django believes the schema is after this migration, so the
# model and the migration graph agree (the makemigrations --check CI gate).
_STATE = [
    migrations.AddField(
        model_name="archivegap",
        name="provider",
        field=models.CharField(default="rainviewer", max_length=20),
    ),
    migrations.AddField(
        model_name="radarframe",
        name="id",
        field=models.BigAutoField(primary_key=True, serialize=False),
    ),
    migrations.AlterField(
        model_name="radarframe",
        name="timestamp",
        field=models.BigIntegerField(),
    ),
    migrations.AddIndex(
        model_name="radarframe",
        index=models.Index(fields=["provider", "timestamp"], name="radar_frame_provider_ts_idx"),
    ),
    migrations.AddConstraint(
        model_name="radarframe",
        constraint=models.UniqueConstraint(
            fields=("provider", "timestamp"),
            name="radar_frame_provider_ts_uniq",
        ),
    ),
]


def _forward(_apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "postgresql":
        with conn.cursor() as cursor:
            cursor.execute(_FORWARD_PG)
    else:
        _sqlite_rebuild(schema_editor)


def _reverse(_apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "postgresql":
        with conn.cursor() as cursor:
            cursor.execute(_REVERSE_PG)
    # The sqlite host fallback is one-directional (dev convenience only).


def _sqlite_rebuild(schema_editor):
    """Non-Postgres host fallback: recreate radar_frame with the surrogate PK.

    sqlite cannot DROP a primary key in place; Django's schema editor rebuilds the
    table transparently, so we replay the state operations against the live schema.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE archive_gap ADD COLUMN provider varchar(20) NOT NULL DEFAULT 'rainviewer'")  # noqa: E501
        cursor.executescript(
            """
            CREATE TABLE radar_frame_new (
                id integer PRIMARY KEY AUTOINCREMENT,
                timestamp bigint NOT NULL,
                provider varchar(20) NOT NULL,
                collected_at datetime NOT NULL,
                tile_count smallint NOT NULL,
                status varchar(10) NOT NULL,
                missing text NOT NULL
            );
            INSERT INTO radar_frame_new (timestamp, provider, collected_at, tile_count, status, missing)
                SELECT timestamp, provider, collected_at, tile_count, status, missing FROM radar_frame;
            DROP TABLE radar_frame;
            ALTER TABLE radar_frame_new RENAME TO radar_frame;
            CREATE INDEX radar_frame_timesta_48c392_idx ON radar_frame (timestamp);
            CREATE INDEX radar_frame_provider_ts_idx ON radar_frame (provider, timestamp);
            CREATE UNIQUE INDEX radar_frame_provider_ts_uniq ON radar_frame (provider, timestamp);
            """,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0003_push_subscription"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=_STATE,
            database_operations=[migrations.RunPython(_forward, _reverse)],
        ),
    ]
